name: Build Android CI

on: 
  push:
    tags:
      - 'v[0-9]+.*'
    
jobs:
  build-android:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 7
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: "npm install"
        run: |
          npm ci
      - name: "patch deps"
        run: |
          node ./ci/patch-deps
      - name: "build jsbundle"
        run: |
          npm run bundle-rnjs
      - name: "Setup variables"
        id: build-config
        run: |
          echo '::echo::on'
          echo '::set-output name=is_prerelease::'$(node ./ci/is-prerelease "$(basename ${{ github.ref }})")
          echo '::set-output name=version_name::'$(basename ${{ github.ref }} | sed 's/^v//')
      - name: "Build for Google Play"
        run: |
          [[ -z "${{ steps.build-config.outputs.version_name }}" ]] && exit 13
          npm run play -- --no-daemon
      - name: "Build for Github release"
        run: |
          [[ -z "${{ steps.build-config.outputs.version_name }}" ]] && exit 13
          USE_SPLITBUILD=1 CI_BUILD=1 CI_VERSION_NAME="${{ steps.build-config.outputs.version_name }}" ./gradlew assembleRelease --no-daemon
      - name: "Changelog"
        run: |
           git log -p -n1 -- CHANGELOG.md  | grep -Po '(?<=^\+)(?!\+\+).*' > CHANGELOG_current.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            ./app/build/outputs/apk/release/app-arm64-v8a-release.apk
            ./app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            ./app/build/outputs/apk/release/app-x86_64-release.apk
            ./app/build/outputs/apk/release/app-x86-release.apk
            ./app/build/outputs/bundle/release/app-release.aab
          body: "Update code server version to 4.90.2"
